### PR TITLE
Graphite line format ingester

### PR DESCRIPTION
**Pull request by phxql**
Hi,
i've implemented a Graphite line format ingester. I didn't test it yet, just wanted to have some feedback about the general idea.

### CODE REVIEW

**Comment by FlorianLautenschlager** [comment]
Thx, i will merge this PR.

**Comment by danielkza** [comment]
Are there any instructions on how to use this? How does it work, considering the Graphite protocol uses plain TCP and not HTTP? I see nothing about accepting new connections on a different port, just adding a new listener in Solr, which means no existing Graphite clients can talk to it.

**Comment by phxql** [comment]
Hi, at the moment we implemented the Graphite Line Protocol, but on top of HTTP, not TCP. To get this working with a Graphite client, we need a TCP to HTTP proxy. The other way is to modify the code to open an TCP port, but i'm not sure if that works when running in a Solr context. Unfortunately, the Graphite ingester don't work out of the box.

**Comment by FlorianLautenschlager** [comment]
We can think about to extend the chronix ingester with an TCP port.

**Comment by phxql** [comment]
Will that work when Solr is running in a cluster?

**Comment by FlorianLautenschlager** [comment]
Should work :-)

The chronix ingester just ships the data to the Solr master who handles the replication and sharding.

**Pull request merged**
